//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBCourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contract
    {
        public int ContractId { get; set; }
        public int CustomerID { get; set; }
        public int CarID { get; set; }
        public int ConsultantID { get; set; }
        public string Notres { get; set; }
        public Nullable<System.DateTime> ExpiryDateLease { get; set; }
        public Nullable<System.DateTime> DateDrawingContract { get; set; }
    
        public virtual Car Car { get; set; }
        public virtual Consultant Consultant { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
